---
- hosts: all
  become: no
  gather_facts: yes

  tasks:
   - name: Display the current timestamp in YYYY-MM-DD
     debug:
      var=ansible_date_time.date
      
   - name: Display the hostname
     shell: "hostname -i"
     register: out

   - debug: var=out.stdout_lines   
